# Generated by Django 5.1.4 on 2025-01-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userfollows_alter_user_followed'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
