# Generated by Django 5.1.4 on 2025-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userfollows_alter_user_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile.png', upload_to='profile_pictures/'),
        ),
    ]
